# Generated by Django 5.0.6 on 2024-08-18 04:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
