# Generated by Django 5.0.6 on 2024-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0005_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Haha'), (3, 'Love'), (4, 'Sad')], null=True),
        ),
    ]
