# Generated by Django 5.0.6 on 2024-10-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocial', '0010_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status_report',
            field=models.IntegerField(choices=[(1, 'Chờ xử lý'), (2, 'Đã giải quyết'), (3, 'Bị từ chối')], default=1),
        ),
    ]
